name: SonarQube Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16' # Change this to the latest JDK version you want to use
          distribution: 'adopt' # Can be changed to other vendors like 'zulu', 'temurin', etc.
      - name: Download gradlew
        run: |
          wget https://raw.githubusercontent.com/gradle/gradle/master/gradlew
          chmod +x gradlew
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/classes

