name: SonarQube Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16' # Change this to the latest JDK version you want to use
          distribution: 'adopt' # Can be changed to other vendors like 'zulu', 'temurin', etc.
      - name: Set up Gradle wrapper
        run: |
          ./gradlew wrapper --gradle-version 7.3
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/classes

  sonarQube:
    needs: build
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/classes
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONAR_HOST }}
          login: ${{ secrets.SONAR_TOKEN }}
          projectBaseDir: '/github/workspace'

